---
- hosts: vagrant
  gather_facts: no
  connection: paramiko
  user: pmis
  tasks:
  - action: fireball port=5100

- hosts: vagrant
  gather_facts: no
  connection: fireball
  port: 5100
  tasks:
  - git: repo=git@github.com:adieyal/PMIS.git dest=/home/pmis/deploy
  - command: /home/pmis/deploy/bin/collectstatic.sh
  - file: dest=/home/pmis/deploy/logs state=directory
  - command: bash -c 'source /etc/bash_completion.d/virtualenvwrapper; mkvirtualenv pmis'
  - command: /home/pmis/.virtualenvs/pmis/bin/easy_install -U distribute
  - pip: requirements=/home/pmis/deploy/requirements.txt virtualenv=/home/pmis/.virtualenvs/pmis
  - django_manage: >
        app_path=/home/pmis/deploy
        command=syncdb
        database=default
        settings=project.settings.production
        virtualenv=/home/pmis/.virtualenvs/pmis
    environment:
        SECRET_KEY: pmis-production-key
