---
- hosts: vagrant
  gather_facts: no
  connection: paramiko
  user: pmis
  tasks:
  - action: fireball port=5100

- hosts: vagrant
  gather_facts: no
  connection: fireball
  port: 5100
  tasks:
  - command: whoami
  - git: repo=git@github.com:adieyal/PMIS.git dest=/home/pmis/deploy
  - easy_install: name=distribute virtualenv=/home/pmis/.virtualenvs/pmis
  - pip: requirements=/home/pmis/deploy/requirements.txt virtualenv=/home/pmis/.virtualenvs/pmis
  - django_manage: >
    app_path=/home/pmis/deploy
    command=syncdb
    database=default
    settings=project.settings.production
