# http://jpmens.net/2012/10/01/dramatically-speeding-up-ansible-runs/
---
- hosts: all
  gather_facts: no
  connection: ssh
  user: vagrant
  sudo: yes

  tasks:
  - apt: pkg=$item
    with_items:
      - build-essential
      - python-setuptools
      - git
      - python-dev
      - libzmq-dev

  - easy_install: name=pip

  - pip: name=$item
    with_items:
      - pyzmq
      - pyasn1
      - PyCrypto
      - python-keyczar

