---
- hosts: vagrant
  gather_facts: no
  connection: ssh
  user: vagrant
  sudo: yes

  tasks:
  - action: fireball

- hosts: vagrant
  gather_facts: no
  connection: fireball
  vars:
    password: $1$SomeSalt$xg7BaTdMtPm8RHKM70Veb0

  tasks:
  - apt: pkg=$item
    with_items:
      - git
      - rsync
      - virtualenvwrapper

  - user: name=pmis password=$password groups=admin append=yes comment="PMIS Pseudouser" generate_ssh_key=yes shell=/bin/bash
  - local_action: command rsync -rlpgoD templates/home/ pmis@$inventory_hostname:.

- hosts: vagrant
  gather_facts: no
  connection: ssh
  user: vagrant
  sudo: yes
  sudo_user: pmis

  tasks:
  - pip: name=django virtualenv=/home/pmis/.virtualenvs/pmis
  - git: repo=git://github.com/adieyal/PMIS.git dest=/home/pmis/deploy/develop version=develop
  - git: repo=git://github.com/adieyal/PMIS.git dest=/home/pmis/deploy/master version=master
