---
- hosts: vagrant
  gather_facts: no
  connection: paramiko
  user: vagrant
  sudo: yes
  tasks:
  - action: fireball

- hosts: vagrant
  gather_facts: yes
  connection: fireball
  vars:
      connections: 1024
  tasks:
  # Copy the supervisor config file across, and ensure the service is started
  # and the application is running
  - copy: src=templates/supervisor.conf dest=/etc/supervisor/conf.d/pmis.conf
  - service: name=supervisor state=started
  - command: supervisorctl reread
  - command: supervisorctl update

  # Copy nginx config files across
  - template: src=templates/nginx.j2 dest=/etc/nginx/nginx.conf
  - copy: src=templates/nginx-site.conf dest=/etc/nginx/sites-available/default
  - service: name=nginx state=restarted
